### ISSUE TITLE
Wrong error message while PG.connect on Windows

### ISSUE THREAD

**Issue by larskanis** [ged/ruby-pg#404]
On Windows the async API doesn't raise a correct error message. If a wrong database name was provided this looks like so:

```ruby
$ irb -Ilib -rpg
irb(main):001:0> c=PG.connect dbname:'Entwicklun'
c:/Users/kanis/ruby-pg/lib/pg/connection.rb:509:in `async_connect_or_reset': server closed the connection unexpectedly (PG::ConnectionBad)
        This probably means the server terminated abnormally
        before or while processing the request.
        from c:/Users/kanis/ruby-pg/lib/pg/connection.rb:529:in `async_connect'
        from c:/Users/kanis/ruby-pg/lib/pg.rb:67:in `connect'
        from (irb):1:in `<main>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
        from C:/Ruby30-x64/bin/irb.cmd:31:in `load'
        from C:/Ruby30-x64/bin/irb.cmd:31:in `<main>'

irb(main):002:0> PG::Connection.async_api=false
irb(main):003:0> c=PG.connect dbname:'Entwicklun'
c:/Users/kanis/ruby-pg/lib/pg.rb:67:in `initialize': FATAL:  Datenbank \xBBEntwicklun\xAB existiert nicht (PG::ConnectionBad)
        from c:/Users/kanis/ruby-pg/lib/pg.rb:67:in `new'
```

In contrast it raises the right message when `async_api=false` is set or when running on Linux.

**Comment by larskanis** [comment]
This issue is discussed in postgresql hackers list here: https://www.postgresql.org/message-id/90b34057-4176-7bb0-0dbb-9822a5f6425b%40greiz-reinsdorf.de

**Comment by larskanis** [comment]
It only happens when both client and server are running on Windows.

**Comment by larskanis** [comment]
The patch has landed on postgres master branch and will be backported to all active branches. See https://github.com/postgres/postgres/commit/4cd2928543c1148278f8c1f393ee58dd72816df0
