### ISSUE TITLE
TruffleRuby: Fail to run "External LLVMFunction init_pg_tuple cannot be found"

### ISSUE THREAD

**Issue by yosiat** [ged/ruby-pg#414]
Hi!

I am trying out truffleruby on my rails app and I am getting this error -
```
Bundler::GemRequireError:
  There was an error while trying to load the gem 'torque-postgresql'.
  Gem Load Error is: External LLVMFunction init_pg_tuple cannot be found. (com.oracle.truffle.llvm.runtime.except.LLVMLinkerException)
  Translated to internal error
  Backtrace for gem load error is:
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/pg-1.2.3/ext/pg.c:675:in `Init_pg_ext'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `gem_original_require'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/pg-1.2.3/lib/pg.rb:5:in `<top (required)>'
  <internal:core> core/kernel.rb:234:in `gem_original_require'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:4:in `<top (required)>'
  <internal:core> core/kernel.rb:234:in `gem_original_require'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/torque-postgresql-2.2.2/lib/torque/postgresql.rb:9:in `<top (required)>'
  <internal:core> core/kernel.rb:234:in `gem_original_require'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/torque-postgresql-2.2.2/lib/torque-postgresql.rb:1:in `<top (required)>'
  <internal:core> core/kernel.rb:234:in `gem_original_require'
  /Users/yosi/.rvm/rubies/truffleruby-21.3.0/lib/mri/bundler/runtime.rb:74:in `block (2 levels) in require'
  /Users/yosi/.rvm/rubies/truffleruby-21.3.0/lib/mri/bundler/runtime.rb:69:in `each'
  /Users/yosi/.rvm/rubies/truffleruby-21.3.0/lib/mri/bundler/runtime.rb:69:in `block in require'
  /Users/yosi/.rvm/rubies/truffleruby-21.3.0/lib/mri/bundler/runtime.rb:58:in `each'
  /Users/yosi/.rvm/rubies/truffleruby-21.3.0/lib/mri/bundler/runtime.rb:58:in `require'
  /Users/yosi/.rvm/rubies/truffleruby-21.3.0/lib/mri/bundler.rb:174:in `require'
  /Users/yosi/code/work/rails-app/config/application.rb:33:in `<top (required)>'
  <internal:core> core/kernel.rb:293:in `require_relative'
  /Users/yosi/code/work/rails-app/config/environment.rb:4:in `<top (required)>'
  <internal:core> core/kernel.rb:234:in `gem_original_require'
  /Users/yosi/code/work/rails-app/spec/spec_helper.rb:17:in `<top (required)>'
  <internal:core> core/kernel.rb:234:in `gem_original_require'
  /Users/yosi/code/work/rails-app/spec/models/model_spec.rb:3:in `<top (required)>'
  <internal:core> core/kernel.rb:376:in `load'
  <internal:core> core/kernel.rb:376:in `load'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2112:in `load_file_handling_errors'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:1615:in `block in load_spec_files'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:1613:in `each'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:1613:in `load_spec_files'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:102:in `setup'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:86:in `run'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
  /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<top (required)>'
  <internal:core> core/kernel.rb:376:in `load'
  <internal:core> core/kernel.rb:376:in `load'
  ./bin/rspec:3:in `<main>'
  Bundler Error Backtrace:
# /Users/yosi/.rvm/rubies/truffleruby-21.3.0/lib/mri/bundler/runtime.rb:77:in `block (2 levels) in require'
# /Users/yosi/.rvm/rubies/truffleruby-21.3.0/lib/mri/bundler/runtime.rb:69:in `each'
# /Users/yosi/.rvm/rubies/truffleruby-21.3.0/lib/mri/bundler/runtime.rb:69:in `block in require'
# /Users/yosi/.rvm/rubies/truffleruby-21.3.0/lib/mri/bundler/runtime.rb:58:in `each'
# /Users/yosi/.rvm/rubies/truffleruby-21.3.0/lib/mri/bundler/runtime.rb:58:in `require'
# /Users/yosi/.rvm/rubies/truffleruby-21.3.0/lib/mri/bundler.rb:174:in `require'
# ./config/application.rb:33:in `<top (required)>'
# <internal:core> core/kernel.rb:293:in `require_relative'
# ./config/environment.rb:4:in `<top (required)>'
# <internal:core> core/kernel.rb:234:in `gem_original_require'
# ./spec/spec_helper.rb:17:in `<top (required)>'
# <internal:core> core/kernel.rb:234:in `gem_original_require'
# ./spec/models/model_spec.rb:3:in `<top (required)>'
# <internal:core> core/kernel.rb:376:in `load'
# <internal:core> core/kernel.rb:376:in `load'
# <internal:core> core/kernel.rb:376:in `load'
# <internal:core> core/kernel.rb:376:in `load'
# ------------------
# --- Caused by: ---
# RuntimeError:
#   External LLVMFunction init_pg_tuple cannot be found. (com.oracle.truffle.llvm.runtime.except.LLVMLinkerException)
#   Translated to internal error
#   /Users/yosi/.rvm/gems/truffleruby-21.3.0/gems/pg-1.2.3/ext/pg.c:675:in `Init_pg_ext'
```

Mac: `Darwin YosiAttias.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64`
Ruby: `truffleruby 21.3.0, like ruby 2.7.4, GraalVM CE Native [x86_64-darwin]`
Install pg with `gem install pg -v '1.2.3' --  --with-pg-dir=$(brew --prefix postgresql@13)`

**Comment by larskanis** [comment]
Could you please update to pg-1.3.0.rc2 ? It should successfully run on Truffleruby.

**Comment by yosiat** [comment]
@larskanis the test fails on something else (interception gem) - so I am good here, thanks!
