### ISSUE TITLE
`PG::Connection` test failures

### ISSUE THREAD

**Issue by voxik** [ged/ruby-pg#421]
Trying to build updated PG package on Fedora, I observer following test failures:

~~~
Failures:

  1) PG::Connection PG::Connection#parse_connect_args accepts an URI and adds hostaddr
     Failure/Error: expect( string ).to match( %r{^postgresql://www.ruby-lang.org,nonexisting-domaiiin.xyz,localhost\?hostaddr=\d+\.\d+\.\d+\.\d+%2C%2C(%3A%3A1|127\.0\.0\.1)} )

       expected "postgresql://www.ruby-lang.org,nonexisting-domaiiin.xyz,localhost?hostaddr=%2C%2C%3A%3A1&fallback_application_name=%2Fusr%2Fbin%2Frspec" to match /^postgresql:\/\/www.ruby-lang.org,nonexisting-domaiiin.xyz,localhost\?hostaddr=\d+\.\d+\.\d+\.\d+%2C%2C(%3A%3A1|127\.0\.0\.1)/
       Diff:
       @@ -1,2 +1,2 @@
       -/^postgresql:\/\/www.ruby-lang.org,nonexisting-domaiiin.xyz,localhost\?hostaddr=\d+\.\d+\.\d+\.\d+%2C%2C(%3A%3A1|127\.0\.0\.1)/
       +"postgresql://www.ruby-lang.org,nonexisting-domaiiin.xyz,localhost?hostaddr=%2C%2C%3A%3A1&fallback_application_name=%2Fusr%2Fbin%2Frspec"
     # ./spec/pg/connection_spec.rb:156:in `block (3 levels) in <top (required)>'
     # /builddir/build/BUILD/spec/helpers.rb:34:in `block in included'

  2) PG::Connection PG::Connection#parse_connect_args can create a connection option string from an option string and a hash
     Failure/Error: expect( optstring ).to match( /(^|\s)hostaddr='\d+\.\d+\.\d+\.\d+,,(::1|127\.0\.0\.1)'/ )

       expected "dbname=original user='jrandom' host='www.ruby-lang.org,nonexisting-domaiiin.xyz,localhost' hostaddr=',,::1' fallback_application_name='/usr/bin/rspec'" to match /(^|\s)hostaddr='\d+\.\d+\.\d+\.\d+,,(::1|127\.0\.0\.1)'/
       Diff:
       @@ -1,2 +1,2 @@
       -/(^|\s)hostaddr='\d+\.\d+\.\d+\.\d+,,(::1|127\.0\.0\.1)'/
       +"dbname=original user='jrandom' host='www.ruby-lang.org,nonexisting-domaiiin.xyz,localhost' hostaddr=',,::1' fallback_application_name='/usr/bin/rspec'"
     # ./spec/pg/connection_spec.rb:116:in `block (3 levels) in <top (required)>'
     # /builddir/build/BUILD/spec/helpers.rb:34:in `block in included'

  3) running with sync_* methods PG::Connection PG::Connection#parse_connect_args accepts an URI and adds hostaddr
     Failure/Error: expect( string ).to match( %r{^postgresql://www.ruby-lang.org,nonexisting-domaiiin.xyz,localhost\?hostaddr=\d+\.\d+\.\d+\.\d+%2C%2C(%3A%3A1|127\.0\.0\.1)} )

       expected "postgresql://www.ruby-lang.org,nonexisting-domaiiin.xyz,localhost?hostaddr=%2C%2C%3A%3A1&fallback_application_name=%2Fusr%2Fbin%2Frspec" to match /^postgresql:\/\/www.ruby-lang.org,nonexisting-domaiiin.xyz,localhost\?hostaddr=\d+\.\d+\.\d+\.\d+%2C%2C(%3A%3A1|127\.0\.0\.1)/
       Diff:
       @@ -1,2 +1,2 @@
       -/^postgresql:\/\/www.ruby-lang.org,nonexisting-domaiiin.xyz,localhost\?hostaddr=\d+\.\d+\.\d+\.\d+%2C%2C(%3A%3A1|127\.0\.0\.1)/
       +"postgresql://www.ruby-lang.org,nonexisting-domaiiin.xyz,localhost?hostaddr=%2C%2C%3A%3A1&fallback_application_name=%2Fusr%2Fbin%2Frspec"
     # ./spec/pg/connection_spec.rb:156:in `block (4 levels) in <top (required)>'
     # /builddir/build/BUILD/spec/helpers.rb:34:in `block in included'

  4) running with sync_* methods PG::Connection PG::Connection#parse_connect_args can create a connection option string from an option string and a hash
     Failure/Error: expect( optstring ).to match( /(^|\s)hostaddr='\d+\.\d+\.\d+\.\d+,,(::1|127\.0\.0\.1)'/ )

       expected "dbname=original user='jrandom' host='www.ruby-lang.org,nonexisting-domaiiin.xyz,localhost' hostaddr=',,::1' fallback_application_name='/usr/bin/rspec'" to match /(^|\s)hostaddr='\d+\.\d+\.\d+\.\d+,,(::1|127\.0\.0\.1)'/
       Diff:
       @@ -1,2 +1,2 @@
       -/(^|\s)hostaddr='\d+\.\d+\.\d+\.\d+,,(::1|127\.0\.0\.1)'/
       +"dbname=original user='jrandom' host='www.ruby-lang.org,nonexisting-domaiiin.xyz,localhost' hostaddr=',,::1' fallback_application_name='/usr/bin/rspec'"
     # ./spec/pg/connection_spec.rb:116:in `block (4 levels) in <top (required)>'
     # /builddir/build/BUILD/spec/helpers.rb:34:in `block in included'

Finished in 24.7 seconds (files took 0.1988 seconds to load)
838 examples, 4 failures

Failed examples:

rspec ./spec/pg/connection_spec.rb[1:3:10] # PG::Connection PG::Connection#parse_connect_args accepts an URI and adds hostaddr
rspec ./spec/pg/connection_spec.rb[1:3:6] # PG::Connection PG::Connection#parse_connect_args can create a connection option string from an option string and a hash
rspec ./spec/pg/connection_sync_spec.rb[1:1:3:10] # running with sync_* methods PG::Connection PG::Connection#parse_connect_args accepts an URI and adds hostaddr
rspec ./spec/pg/connection_sync_spec.rb[1:1:3:6] # running with sync_* methods PG::Connection PG::Connection#parse_connect_args can create a connection option string from an option string and a hash
~~~

The thing is that the test suite is executed in Fedora builders with disabled networking. I'll got with the following workaround:

~~~
$ sed -i -r 's|\\d\+\\\.\\d\+\\\.\\d\+\\\.\\d\+|(\0)?|' spec/pg/connection_spec.rb
~~~

Not sure if that would be the right fix, though.

**Comment by larskanis** [comment]
4 times the same issue: the hostname `www.ruby-lang.org` can not be resolved by DNS. Is it possible to make it resolve in your CI environment (by /etc/hosts or so) or can you disable these tests?

**Comment by larskanis** [comment]
Maybe your workaround is OK as well.

**Comment by voxik** [comment]
The `/etc/resolv.conf` is completely empty on purpose. I am fine disabling the test cases or using my workaround. I just wanted to double check with you. I'll completely understand if you close this as WONTFIX.

**Comment by larskanis** [comment]
Alright!
