### ISSUE TITLE
Flaky schedule tests

### ISSUE THREAD

**Issue by voxik** [ged/ruby-pg#424]
Trying to execute the test suite during build of PG package on Fedora, I quite often observe the following errors:

~~~
  1) with a Fiber scheduler can send lots of data per put_copy_data
     Failure/Error: raise("scheduler timeout in:\n#{th.backtrace.join("\n")}")
     RuntimeError:
       scheduler timeout in:
       /builddir/build/BUILD/spec/helpers/scheduler.rb:51:in `select'
       /builddir/build/BUILD/spec/helpers/scheduler.rb:51:in `run'
       /builddir/build/BUILD/spec/helpers/scheduler.rb:111:in `close'
     # ./spec/pg/scheduler_spec.rb:42:in `thread_with_timeout'
     # ./spec/pg/scheduler_spec.rb:47:in `run_with_scheduler'
     # ./spec/pg/scheduler_spec.rb:175:in `block (2 levels) in <top (required)>'
     # /builddir/build/BUILD/spec/helpers.rb:34:in `block in included'
  2) with a Fiber scheduler should convert strings and parameters to #prepare and #exec_prepared
     Failure/Error: raise("scheduler timeout in:\n#{th.backtrace.join("\n")}")
     RuntimeError:
       scheduler timeout in:
       /builddir/build/BUILD/spec/helpers/scheduler.rb:51:in `select'
       /builddir/build/BUILD/spec/helpers/scheduler.rb:51:in `run'
       /builddir/build/BUILD/spec/helpers/scheduler.rb:111:in `close'
     # ./spec/pg/scheduler_spec.rb:42:in `thread_with_timeout'
     # ./spec/pg/scheduler_spec.rb:47:in `run_with_scheduler'
     # ./spec/pg/scheduler_spec.rb:233:in `block (2 levels) in <top (required)>'
     # /builddir/build/BUILD/spec/helpers.rb:34:in `block in included'
  3) with a Fiber scheduler waits when sending query data
     Failure/Error: raise("scheduler timeout in:\n#{th.backtrace.join("\n")}")
     RuntimeError:
       scheduler timeout in:
       /builddir/build/BUILD/spec/helpers/scheduler.rb:51:in `select'
       /builddir/build/BUILD/spec/helpers/scheduler.rb:51:in `run'
       /builddir/build/BUILD/spec/helpers/scheduler.rb:111:in `close'
     # ./spec/pg/scheduler_spec.rb:42:in `thread_with_timeout'
     # ./spec/pg/scheduler_spec.rb:47:in `run_with_scheduler'
     # ./spec/pg/scheduler_spec.rb:90:in `block (2 levels) in <top (required)>'
     # /builddir/build/BUILD/spec/helpers.rb:34:in `block in included'
~~~

I have already tried to increase the timeouts, but I don't think increasing them further would help.

**Comment by voxik** [comment]
Actually, the armv7hl might be the culprit. So that might be related to the performance of this architecture.

**Comment by larskanis** [comment]
Yes, the tests of the nonblocking mode are timing dependent. This is better than no tests, but it's also annoying to have test failures.

I think the only way to make it timing independent is to control the data flow by intercepting the TCP connection to the PostgreSQL server. This is how we test the compatibility to Fiber.scheduler and it works very reliable: https://github.com/ged/ruby-pg/blob/master/spec/helpers/tcp_gate_scheduler.rb

**Comment by jackorp** [comment]
There is a test suffering a similar timing problem in spec/pg/connection_spec.rb:
```
  1) running with sync_* methods PG::Connection in nonblocking mode needs to flush data after send_query
     Failure/Error: expect( res ).to be_falsey
       expected: falsey value
            got: true
     # ./spec/pg/connection_spec.rb:562:in `block (4 levels) in <top (required)>'
     # /builddir/build/BUILD/spec/helpers.rb:35:in `block in included'`
```
This test does pass reliably only on x86_64, the rest of the platforms we build against in Fedora (ppc64le, s390x, aarch64, i686) are failing more often than not.

There seems to have been an improvement on the scheduler tests with the TCPGate helper, would something like that be possible for this type of tests as well?
