### ISSUE TITLE
connection to server at "::1", port 5432 failed: Connection refused (PG::ConnectionBad) in PG 1.3.0

### ISSUE THREAD

**Issue by chrisgow** [ged/ruby-pg#433]
Hi,

I've started to intermittently receive the following connection error after upgrading to the 1.3.x pg gem:

```
pg-1.3.2/lib/pg/connection.rb:637:in `async_connect_or_reset': connection to server at "::1", port 5432 failed: Connection refused (PG::ConnectionBad)
	Is the server running on that host and accepting TCP/IP connections?
```

It seems to occur on Mac where PostgreSQL is running in a Docker container.

Error using pg 1.3.0:
```ruby
chrisg@MacBook-Pro ~> irb
2.7.4 :001 > require 'pg'
 => true
2.7.4 :002 > PG::VERSION
 => "1.3.0"
2.7.4 :003 > conn = PG.connect(host: 'localhost', dbname: 'database', user: 'user_login', password: 'secret')
Traceback (most recent call last):
        7: from /Users/chrisg/.rvm/rubies/ruby-2.7.4/bin/irb:23:in `<main>'
        6: from /Users/chrisg/.rvm/rubies/ruby-2.7.4/bin/irb:23:in `load'
        5: from /Users/chrisg/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        4: from (irb):3
        3: from /Users/chrisg/.rvm/gems/ruby-2.7.4@pg13/gems/pg-1.3.0/lib/pg.rb:67:in `connect'
        2: from /Users/chrisg/.rvm/gems/ruby-2.7.4@pg13/gems/pg-1.3.0/lib/pg/connection.rb:705:in `new'
        1: from /Users/chrisg/.rvm/gems/ruby-2.7.4@pg13/gems/pg-1.3.0/lib/pg/connection.rb:636:in `async_connect_or_reset'
PG::ConnectionBad (connection to server at "::1", port 5432 failed: Connection refused)
	Is the server running on that host and accepting TCP/IP connections?
2.7.4 :004 >
```

Successful connection in 1.2.3:

```ruby
chrisg@MacBook-Pro ~> irb
2.7.4 :001 > require 'pg'
 => true
2.7.4 :002 > PG::VERSION
 => "1.2.3"
2.7.4 :003 > conn = PG.connect(host: 'localhost', dbname: 'database', user: 'user_login', password: 'secret')
 => #<PG::Connection:0x00007fb9cf8ccf90>
2.7.4 :004 >
```

It seems to only occur when resolving `localhost`. There is no entry in my `/etc/hosts` file for `::1`, so I do not know where that is being picked up

**Comment by larskanis** [comment]
pg-1.3.x changed address resolution to be done in [Ruby space](https://github.com/ged/ruby-pg/blob/1cfc50cce59c649ebbeb24a0ce96889bf2ca3354/lib/pg/connection.rb#L153) instead of in libpq. Not sure why they resolve differently, but you can force IPv4 if you add this line to your local `/etc/hosts` :
```
127.0.0.1 localhost
```

**Comment by chrisgow** [comment]
Huh. I have that entry in my `/etc/hosts` file and `IPSocket.getaddress("localhost")` still resolves to `::1`. So, this appears to be how Ruby is resolving that address and not pg itself. Thanks for the hint to `IPSocket`. I will close this issue
