### ISSUE TITLE
UNIX domain socket no longer supported with relative path

### ISSUE THREAD

**Issue by jc00ke** [ged/ruby-pg#484]
I'm not exactly sure where the change was, but for years I could connect with the following connection string: `postgres:///my_app_dev?host=.direnv/postgres`. After upgrading from `1.2.3` to `1.4.3` I could no longer use that relative path `.direnv/postgres`. Once I switched to `/home/jesse/path/to/my_app/.direnv/postgres` it worked again.

**Comment by jc00ke** [comment]
Sorry, I should have at least provided the error:

```
  ➜ rails c
  Running via Spring preloader in process 3017783
  Loading development environment (Rails 7.0.3.1)
  irb(main):001:0> ENV["DATABASE_URL"]
  => "postgres:///my_app_dev?host=.direnv/postgres"
  irb(main):002:0> User.count
  /home/jesse/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/connection_adapters/postgresql_adapter.rb:87:in `rescue
  in new_client': could not translate host name ".direnv/postgres" to address: Name or service not known (ActiveRecord::ConnectionNotEstablished)
  /home/jesse/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/pg-1.4.3/lib/pg/connection.rb:751:in `connect_to_hosts': could not translate host name ".direnv
  /postgres" to address: Name or service not known (PG::ConnectionBad)
  irb(main):003:0>

  irb(main):004:0> PG::Connection.new(host: ".direnv/postgres")
  /home/jesse/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/pg-1.4.3/lib/pg/connection.rb:751:in `connect_to_hosts': could not translate host name ".direnv
  /postgres" to address: Name or service not known (PG::ConnectionBad)
  irb(main):005:0> PG::Connection.new(host: Pathname.getwd + ".direnv/postgres")
  => #<PG::Connection:0x00007f453d16dff8 @calls_to_put_copy_data=0, @last_status=4>
  irb(main):006:0>

```

**Comment by larskanis** [comment]
I can not reproduce that pg-1.2.3 connects with a relative path to a UnixSocket file. I always get a `could not translate host name` error.

The libpq documentation states, that only an absolute path is interpret as a UnixSocket name: https://www.postgresql.org/docs/14/libpq-connect.html#LIBPQ-PARAMKEYWORDS

Also the libpq source code checks only for an absolute path: https://github.com/postgres/postgres/blob/051b096b8dd3b65f8e4528a8cd24a8702646e8b2/src/include/libpq/pqcomm.h#L57

**Comment by jc00ke** [comment]
Hmm, interesting. What information would be beneficial to collect? I can also attempt to bisect from last known version that worked on my machine.

**Comment by cbandy** [comment]
> Also the libpq source code checks only for an absolute path: https://github.com/postgres/postgres/blob/051b096b8dd3b65f8e4528a8cd24a8702646e8b2/src/include/libpq/pqcomm.h#L57

🤔 I see similar code going _way_ back: [postgres/postgres@d46e643/src/interfaces/libpq/fe-connect.c](https://github.com/postgres/postgres/commit/d46e6438225d8741100dc400a4a63c87799f0945#diff-8d819454e061b9d4cdae9c8922ded05753a629d70f2ac1de1d4f6d5a4aeb7f68)

**Comment by jc00ke** [comment]
I'm now wondering if there was a change in Rails/AR. Maybe it detects a relative path and yields an absolute path. I'll try to find some time to investigate that.

**Comment by larskanis** [comment]
@jc00ke You could try to reproduce this issue with ruby-pg instead of AR with something like so:
```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem "pg", "1.2.3" # or "1.4.4"
end

puts "pg version: #{PG::VERSION}"

conn = PG.connect("postgres:///my_app_dev?host=.direnv/postgres")
p conn.host
```

**Comment by jc00ke** [comment]
I can't track it down exactly, but it's from a change between ActiveRecord 7.0.0.alpha2 and 7.0.0.rc1. I'll go looking over there to see if it's worth reporting, but `pg` is getting the absolute path when my repro works, so not an issue here.

For the curious:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem "pg", "1.4.4"
  alpha_or_rc = ENV["BUSTED"] ? "rc1" : "alpha2"
  gem "activerecord", "7.0.0.#{alpha_or_rc}"
  gem "pry", "~> 0.13.1"
end

require "active_record"
require "pry"

puts "pg version: #{PG::VERSION}"
puts "AR version: #{ActiveRecord.version()}"

host = ".direnv/postgres"
url = "postgres:///pg?host=#{host}"

pool = ActiveRecord::Base.establish_connection(
  adapter: "postgresql",
  url: url
)
p pool.db_config

binding.pry if ENV["DEBUG"]
conn = ActiveRecord::Base.connection.raw_connection
p conn.host
```

```
~/pg via 💎 v2.7.5 took 2s
❯ ruby pg.rb
pg version: 1.4.4
AR version: 7.0.0.alpha2
#<ActiveRecord::DatabaseConfigurations::UrlConfig:0x000055624e927c40 @env_name="default_env", @name="primary", @configuration_hash={:adapter=>"postgresql", :
database=>"pg"}, @url="postgres:///pg?host=.direnv/postgres">
"/home/jesse/pg/.direnv/postgres"
~/pg via 💎 v2.7.5
➜ BUSTED=1 ruby pg.rb
pg version: 1.4.4
AR version: 7.0.0.rc1
#<ActiveRecord::DatabaseConfigurations::UrlConfig:0x00005600c1c20f70 @env_name="default_env", @name="primary", @configuration_hash={:adapter=>"postgresql", :
database=>"pg", :host=>".direnv/postgres"}, @url="postgres:///pg?host=.direnv/postgres">
Traceback (most recent call last):
        16: from pg.rb:27:in `<main>'
        15: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_handling.rb:280:in `conne
ction'
        14: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_handling.rb:313:in `retri
eve_connection'
        13: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_adapters/abstract/connect
ion_handler.rb:211:in `retrieve_connection'
        12: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_adapters/abstract/connect
ion_pool.rb:181:in `connection'
        11: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_adapters/abstract/connect
ion_pool.rb:341:in `checkout'
        10: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_adapters/abstract/connect
ion_pool.rb:640:in `acquire_connection'
         9: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_adapters/abstract/connect
ion_pool.rb:679:in `try_to_checkout_new_connection'
         8: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_adapters/abstract/connect
ion_pool.rb:700:in `checkout_new_connection'
         7: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_adapters/abstract/connect
ion_pool.rb:656:in `new_connection'
         6: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_adapters/abstract/connect
ion_pool.rb:656:in `public_send'
         5: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_adapters/postgresql_adapt
er.rb:37:in `postgresql_connection'
         4: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_adapters/postgresql_adapt
er.rb:78:in `new_client'
         3: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/pg-1.4.4/lib/pg.rb:69:in `connect'
         2: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/pg-1.4.4/lib/pg/connection.rb:695:in `new'
         1: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/pg-1.4.4/lib/pg/connection.rb:754:in `connect_to_hosts'
/home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/pg-1.4.4/lib/pg/connection.rb:754:in `connect_start': could not translate host name ".direnv/p
ostgres" to address: Name or service not known (PG::ConnectionBad)
        13: from pg.rb:27:in `<main>'
        12: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_handling.rb:280:in `conne
ction'
        11: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_handling.rb:313:in `retri
eve_connection'
        10: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_adapters/abstract/connect
ion_handler.rb:211:in `retrieve_connection'
         9: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_adapters/abstract/connect
ion_pool.rb:181:in `connection'
         8: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_adapters/abstract/connect
ion_pool.rb:341:in `checkout'
         7: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_adapters/abstract/connect
ion_pool.rb:640:in `acquire_connection'
         6: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_adapters/abstract/connect
ion_pool.rb:679:in `try_to_checkout_new_connection'
         5: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_adapters/abstract/connect
ion_pool.rb:700:in `checkout_new_connection'
         4: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_adapters/abstract/connect
ion_pool.rb:656:in `new_connection'
         3: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_adapters/abstract/connect
ion_pool.rb:656:in `public_send'
         2: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_adapters/postgresql_adapt
er.rb:37:in `postgresql_connection'
         1: from /home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_adapters/postgresql_adapt
er.rb:77:in `new_client'
/home/jesse/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.rc1/lib/active_record/connection_adapters/postgresql_adapter.rb:87:in `resc
ue in new_client': could not translate host name ".direnv/postgres" to address: Name or service not known (ActiveRecord::ConnectionNotEstablished)
~/pg via 💎 v2.7.5
❯
```

**Comment by jc00ke** [comment]
Update: I figured it out and tracked it down to a change in how ActiveRecord prepares the config URL. I'll write it up and make sure to link it here for those that are interested.

**Comment by jc00ke** [comment]
You all are correct that `postgres:///my_app_dev?host=.direnv/postgres` is an invalid URI because the `host`, if a UNIX domain socket, must be an absolute path. So, why was my setup with that URI working for years? This commit show us why: https://github.com/rails/rails/commit/c9b25c89ae4372008be0380df6a659d8989ec181

`query_hash.merge` would drop the `host` param, and then `libpg` would, unbeknownst to me (but this makes sense!) fall back to `$PGHOST` env var which was set by [per-project Postgres config](https://jamey.thesharps.us/2019/05/29/per-project-postgres/) to `$(pwd)/postgres` which became `/home/jesse/path/to/my_app/.direnv/postgres`.

My setup broke after https://github.com/rails/rails/commit/c9b25c89ae4372008be0380df6a659d8989ec181 because `query_hash.reverse_merge` would do the right thing and properly pass on `host`, which as said before, as a relative path, was invalid!

I was surprised to see this break between an alpha and an rc for something that had worked for years, but it's better that I clean this all up anyway. Thank you all for helping me sort through it (@larskanis your inline Gemfile technique was :kissing_closed_eyes: :ok_hand:) and I hope that this can help someone that runs into this situation in the future (though honestly I may be the unique snowflake :snowflake: :laughing:)

**Comment by larskanis** [comment]
Thank you @jc00ke for following up this issue and sharing this interesting story!
