### ISSUE TITLE
PG 1.5.0 may have broken COPY exports

### ISSUE THREAD

**Issue by askreet** [ged/ruby-pg#526]
The following example fails with:

```
.../lib/ruby/gems/3.2.0/gems/pg-1.5.1/lib/pg/connection.rb:406:in `sync_get_copy_data': no COPY in progress (PG::Error)
	from .../lib/ruby/gems/3.2.0/gems/pg-1.5.1/lib/pg/connection.rb:406:in `get_copy_data'
	from .../lib/ruby/gems/3.2.0/gems/pg-1.5.1/lib/pg/connection.rb:249:in `copy_data'
	from test.rb:8:in `<main>'
```

```ruby
require 'pg'

conn = PG::Connection.new(host: 'localhost', user: 'postgres', password: 'password', port: 5432, dbname: 'dbname')

conn.copy_data('COPY (SELECT * FROM users) TO STDOUT WITH BINARY') do |res|
  loop do
    data = conn.get_copy_data
    break if data.nil?
  end
end
```

This works in 1.4.6. It seems that we call `get_copy_data` [an additional time](https://github.com/ged/ruby-pg/blob/master/lib/pg/connection.rb#L247-L253) as of v1.5.0 to handle some expected padding from PG, but that does not happen on my system.

```
 PostgreSQL 14.6 (Debian 14.6-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
```

**Comment by askreet** [comment]
Thank you for the rapid fix!
