### ISSUE TITLE
Test failures since Linux 6.10.0

### ISSUE THREAD

**Issue by voxik** [ged/ruby-pg#601]
Running test suite for pg 1.5.7 with PostgreSQL 15.6 / 16.3 on Fedora 39+, starting with Linux 6.10.0, I observe this error:

~~~
  1) with a Fiber scheduler can send lots of data per put_copy_data
     Failure/Error:
       		run_with_scheduler(60) do |conn|
       			conn.exec <<-EOSQL
       				CREATE TEMP TABLE copytable (col1 TEXT);
       			EOSQL
       
       			res = nil
       			conn.copy_data( "COPY copytable FROM STDOUT CSV" ) do
       				data = "x" * 1000 * 1000
       				data << "\n"
       				50.times do

     RuntimeError:
       scheduler timeout in:
       /builddir/build/BUILD/spec/helpers/scheduler.rb:57:in `select'
       /builddir/build/BUILD/spec/helpers/scheduler.rb:57:in `run'
       /builddir/build/BUILD/spec/helpers/scheduler.rb:130:in `close'
       /builddir/build/BUILD/spec/helpers/scheduler.rb:114:in `scheduler_close'
     # /builddir/build/BUILD/spec/helpers.rb:620:in `thread_with_timeout'
     # /builddir/build/BUILD/spec/helpers.rb:625:in `run_with_scheduler'
     # ./spec/pg/scheduler_spec.rb:153:in `block (2 levels) in <top (required)>'
     # /builddir/build/BUILD/spec/helpers.rb:56:in `block in included'

Finished in 1 minute 48.55 seconds (files took 0.63329 seconds to load)
983 examples, 1 failure, 2 pending
~~~

And with more recent Linux kernels, starting with 6.10.7, there are 3 errors:

~~~
  1) with a Fiber scheduler can send lots of data per put_copy_data
     Failure/Error:
       		run_with_scheduler(60) do |conn|
       			conn.exec <<-EOSQL
       				CREATE TEMP TABLE copytable (col1 TEXT);
       			EOSQL
       
       			res = nil
       			conn.copy_data( "COPY copytable FROM STDOUT CSV" ) do
       				data = "x" * 1000 * 1000
       				data << "\n"
       				50.times do

     RuntimeError:
       scheduler timeout in:
       /builddir/build/BUILD/spec/helpers/scheduler.rb:57:in `select'
       /builddir/build/BUILD/spec/helpers/scheduler.rb:57:in `run'
       /builddir/build/BUILD/spec/helpers/scheduler.rb:130:in `close'
       /builddir/build/BUILD/spec/helpers/scheduler.rb:114:in `scheduler_close'
     # /builddir/build/BUILD/spec/helpers.rb:620:in `thread_with_timeout'
     # /builddir/build/BUILD/spec/helpers.rb:625:in `run_with_scheduler'
     # ./spec/pg/scheduler_spec.rb:153:in `block (2 levels) in <top (required)>'
     # /builddir/build/BUILD/spec/helpers.rb:56:in `block in included'

  2) with a Fiber scheduler waits when sending query data
     Failure/Error:
       run_with_scheduler do |conn|
       	data = "x" * 1000 * 1000 * 10
       	res = conn.exec_params("SELECT LENGTH($1)", [data])
       	expect(res.values).to eq([[data.length.to_s]])
       end

     RuntimeError:
       scheduler timeout in:
       /builddir/build/BUILD/spec/helpers/scheduler.rb:57:in `select'
       /builddir/build/BUILD/spec/helpers/scheduler.rb:57:in `run'
       /builddir/build/BUILD/spec/helpers/scheduler.rb:130:in `close'
       /builddir/build/BUILD/spec/helpers/scheduler.rb:114:in `scheduler_close'
     # /builddir/build/BUILD/spec/helpers.rb:620:in `thread_with_timeout'
     # /builddir/build/BUILD/spec/helpers.rb:625:in `run_with_scheduler'
     # ./spec/pg/scheduler_spec.rb:43:in `block (2 levels) in <top (required)>'
     # /builddir/build/BUILD/spec/helpers.rb:56:in `block in included'

  3) with a Fiber scheduler should convert strings and parameters to #prepare and #exec_prepared
     Failure/Error:
       run_with_scheduler do |conn|
       	conn.prepare("weiß1", "VALUES( LENGTH($1), 'grün')")
       	data = "x" * 1000 * 1000 * 10
       	r = conn.exec_prepared("weiß1", [data])
       	expect( r.values ).to eq( [[data.length.to_s, 'grün']] )
       end

     RuntimeError:
       scheduler timeout in:
       /builddir/build/BUILD/spec/helpers/scheduler.rb:57:in `select'
       /builddir/build/BUILD/spec/helpers/scheduler.rb:57:in `run'
       /builddir/build/BUILD/spec/helpers/scheduler.rb:130:in `close'
       /builddir/build/BUILD/spec/helpers/scheduler.rb:114:in `scheduler_close'
     # /builddir/build/BUILD/spec/helpers.rb:620:in `thread_with_timeout'
     # /builddir/build/BUILD/spec/helpers.rb:625:in `run_with_scheduler'
     # ./spec/pg/scheduler_spec.rb:211:in `block (2 levels) in <top (required)>'
     # /builddir/build/BUILD/spec/helpers.rb:56:in `block in included'
~~~

I have [reported](https://bugzilla.redhat.com/show_bug.cgi?id=2324182) this against PostgreSQL in Fedora, hoping that this can be reproduced without this gem. Any clue what could be the reason would also be nice. If anything else, please take this as a heads up that there might be issues with some configurations.

**Comment by larskanis** [comment]
Thanks for your notification! It was easy to reproduce this issue with linux-6.11. I think this is fixed now.
